[patch] mongo b&r tweaks (#2052)
Co-authored-by: Sanjay Prabhakar <sanjay.prabhakar@uk.ibm.com>

diff --git a/ibm/mas_devops/roles/mongodb/tasks/providers/community/backup-restore/database-restore.sh.j2 b/ibm/mas_devops/roles/mongodb/tasks/providers/community/backup-restore/database-restore.sh.j2
--- a/ibm/mas_devops/roles/mongodb/tasks/providers/community/backup-restore/database-restore.sh.j2
+++ b/ibm/mas_devops/roles/mongodb/tasks/providers/community/backup-restore/database-restore.sh.j2
@@ -63,8 +63,14 @@ fi
 # Perform restore
 echo "Restoring databases from $TMP_RESTORE_DIR"
 $mongorestore_cmd
-cmdrc=$?
-if [ $cmdrc -ne 0 ]; then
+restore_rc=$?
+
+# Clean up temporary dir
+echo "Cleaning up temporary dir"
+rm -rf $TMP_RESTORE_DIR
+
+
+if [ $restore_rc -ne 0 ]; then
     echo "Error restoring databases. Exiting."
     exit 1
 fi
